<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      //일반적인 예외 처리
      function f2() {
        console.log("f2 start");
        throw new Error("error");
        console.log("f2 end");
      }

      function f1() {
        console.log("f1 함수 시작");
        try {
          f2();
        } catch (e) {
          console.log(e);
        }
        console.log("f1 함수 끝");
      }
      f1();

      function wait(sec) {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            reject("error");
          }, sec * 1000);
        });
      }

      // chain은 같은 객체를 리턴할 때만 가능하다.
      wait(3)
        .catch((e) => {
          console.log("1set catch", e);
        }) //wait함수의 에러를 받음
        .catch((e) => {
          console.log("1set catch", e);
        }); //
    </script>
  </body>
</html>
